/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BImport } from './routes/b'
import { Route as IndexImport } from './routes/index'
import { Route as SmartBImport } from './routes/smart.b'
import { Route as SmartAImport } from './routes/smart.a'
import { Route as MediaBImport } from './routes/media.b'
import { Route as MediaAImport } from './routes/media.a'
import { Route as KioskBImport } from './routes/kiosk.b'
import { Route as KioskAImport } from './routes/kiosk.a'

// Create/Update Routes

const BRoute = BImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SmartBRoute = SmartBImport.update({
  id: '/smart/b',
  path: '/smart/b',
  getParentRoute: () => rootRoute,
} as any)

const SmartARoute = SmartAImport.update({
  id: '/smart/a',
  path: '/smart/a',
  getParentRoute: () => rootRoute,
} as any)

const MediaBRoute = MediaBImport.update({
  id: '/media/b',
  path: '/media/b',
  getParentRoute: () => rootRoute,
} as any)

const MediaARoute = MediaAImport.update({
  id: '/media/a',
  path: '/media/a',
  getParentRoute: () => rootRoute,
} as any)

const KioskBRoute = KioskBImport.update({
  id: '/kiosk/b',
  path: '/kiosk/b',
  getParentRoute: () => rootRoute,
} as any)

const KioskARoute = KioskAImport.update({
  id: '/kiosk/a',
  path: '/kiosk/a',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BImport
      parentRoute: typeof rootRoute
    }
    '/kiosk/a': {
      id: '/kiosk/a'
      path: '/kiosk/a'
      fullPath: '/kiosk/a'
      preLoaderRoute: typeof KioskAImport
      parentRoute: typeof rootRoute
    }
    '/kiosk/b': {
      id: '/kiosk/b'
      path: '/kiosk/b'
      fullPath: '/kiosk/b'
      preLoaderRoute: typeof KioskBImport
      parentRoute: typeof rootRoute
    }
    '/media/a': {
      id: '/media/a'
      path: '/media/a'
      fullPath: '/media/a'
      preLoaderRoute: typeof MediaAImport
      parentRoute: typeof rootRoute
    }
    '/media/b': {
      id: '/media/b'
      path: '/media/b'
      fullPath: '/media/b'
      preLoaderRoute: typeof MediaBImport
      parentRoute: typeof rootRoute
    }
    '/smart/a': {
      id: '/smart/a'
      path: '/smart/a'
      fullPath: '/smart/a'
      preLoaderRoute: typeof SmartAImport
      parentRoute: typeof rootRoute
    }
    '/smart/b': {
      id: '/smart/b'
      path: '/smart/b'
      fullPath: '/smart/b'
      preLoaderRoute: typeof SmartBImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/kiosk/a': typeof KioskARoute
  '/kiosk/b': typeof KioskBRoute
  '/media/a': typeof MediaARoute
  '/media/b': typeof MediaBRoute
  '/smart/a': typeof SmartARoute
  '/smart/b': typeof SmartBRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/kiosk/a': typeof KioskARoute
  '/kiosk/b': typeof KioskBRoute
  '/media/a': typeof MediaARoute
  '/media/b': typeof MediaBRoute
  '/smart/a': typeof SmartARoute
  '/smart/b': typeof SmartBRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/kiosk/a': typeof KioskARoute
  '/kiosk/b': typeof KioskBRoute
  '/media/a': typeof MediaARoute
  '/media/b': typeof MediaBRoute
  '/smart/a': typeof SmartARoute
  '/smart/b': typeof SmartBRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/b'
    | '/kiosk/a'
    | '/kiosk/b'
    | '/media/a'
    | '/media/b'
    | '/smart/a'
    | '/smart/b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/b'
    | '/kiosk/a'
    | '/kiosk/b'
    | '/media/a'
    | '/media/b'
    | '/smart/a'
    | '/smart/b'
  id:
    | '__root__'
    | '/'
    | '/b'
    | '/kiosk/a'
    | '/kiosk/b'
    | '/media/a'
    | '/media/b'
    | '/smart/a'
    | '/smart/b'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BRoute: typeof BRoute
  KioskARoute: typeof KioskARoute
  KioskBRoute: typeof KioskBRoute
  MediaARoute: typeof MediaARoute
  MediaBRoute: typeof MediaBRoute
  SmartARoute: typeof SmartARoute
  SmartBRoute: typeof SmartBRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BRoute: BRoute,
  KioskARoute: KioskARoute,
  KioskBRoute: KioskBRoute,
  MediaARoute: MediaARoute,
  MediaBRoute: MediaBRoute,
  SmartARoute: SmartARoute,
  SmartBRoute: SmartBRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/b",
        "/kiosk/a",
        "/kiosk/b",
        "/media/a",
        "/media/b",
        "/smart/a",
        "/smart/b"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/b": {
      "filePath": "b.tsx"
    },
    "/kiosk/a": {
      "filePath": "kiosk.a.tsx"
    },
    "/kiosk/b": {
      "filePath": "kiosk.b.tsx"
    },
    "/media/a": {
      "filePath": "media.a.tsx"
    },
    "/media/b": {
      "filePath": "media.b.tsx"
    },
    "/smart/a": {
      "filePath": "smart.a.tsx"
    },
    "/smart/b": {
      "filePath": "smart.b.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
