/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SmartImport } from './routes/smart'
import { Route as KioskImport } from './routes/kiosk'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SmartRoute = SmartImport.update({
  id: '/smart',
  path: '/smart',
  getParentRoute: () => rootRoute,
} as any)

const KioskRoute = KioskImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskImport
      parentRoute: typeof rootRoute
    }
    '/smart': {
      id: '/smart'
      path: '/smart'
      fullPath: '/smart'
      preLoaderRoute: typeof SmartImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRoute
  '/smart': typeof SmartRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRoute
  '/smart': typeof SmartRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRoute
  '/smart': typeof SmartRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kiosk' | '/smart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kiosk' | '/smart'
  id: '__root__' | '/' | '/kiosk' | '/smart'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KioskRoute: typeof KioskRoute
  SmartRoute: typeof SmartRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KioskRoute: KioskRoute,
  SmartRoute: SmartRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kiosk",
        "/smart"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kiosk": {
      "filePath": "kiosk.tsx"
    },
    "/smart": {
      "filePath": "smart.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
